[package]
name = "rustafits"
version = "0.1.0"
edition = "2021"

[lib]
name = "fits_converter"
path = "src/lib.rs"

[[bin]]
name = "rustafits"
path = "src/bin/rustafits.rs"

[dependencies]
anyhow = "1.0"

[build-dependencies]
pkg-config = "0.3"
cc = "1.0"
